#include <Keypad.h>
#include <LiquidCrystal.h>
#include <EEPROM.h>
#include <avr/eeprom.h>
#include "RealTime.h"
#include "Types.h"
#include "HW_Interface.h"
#include "HX711.h"
#include "QuickStats.h"
#include "printer.h"
